spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.mapper.xml
  type-aliases-package: com.levent8421.wechat.tools.commons.entity