server:
  port: 9013
spring:
  profiles:
    include: repository,repository-release,web,web-release,resource,resource-release,service,service-release
logging:
  level:
    com.levent8421.wechat.tools: debug